#!/usr/bin/env python3
from __future__ import annotations

import os
from pathlib import Path


def load_env_file(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.exists():
        return data
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        key, _, value = stripped.partition("=")
        data[key.strip()] = value.strip()
    return data


def to_bool(value: str | None, default: bool) -> bool:
    if value is None or value == "":
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def main() -> None:
    repo_root = Path.cwd()
    env_path = repo_root / "config" / "cliproxy-plus.env"
    env = load_env_file(env_path)

    port = int(env.get("CLIPROXY_PORT", "8317"))
    management_key = env.get("CLIPROXY_MANAGEMENT_KEY", "gaoyx123")
    usage_enabled = to_bool(env.get("CLIPROXY_USAGE_STATISTICS_ENABLED"), True)
    pprof_enabled = to_bool(env.get("CLIPROXY_PPROF_ENABLE"), False)
    pprof_addr = env.get("CLIPROXY_PPROF_ADDR", "127.0.0.1:8316")
    api_key = env.get("CLIPROXY_API_KEY", "gaoyx123")

    target_dir = repo_root / "state" / "cliproxy-plus"
    target_dir.mkdir(parents=True, exist_ok=True)
    config_path = target_dir / "config.yaml"

    config_text = f"""# Generated by scripts/services/cliproxy_plus/gen_config.py
host: ''
port: {port}

tls:
  enable: false
  cert: ''
  key: ''

remote-management:
  allow-remote: false
  secret-key: '{management_key}'
  disable-control-panel: false

auth-dir: '/root/.cli-proxy-api'

api-keys:
  - '{api_key}'

debug: false

pprof:
  enable: {'true' if pprof_enabled else 'false'}
  addr: '{pprof_addr}'

logging-to-file: true
logs-max-total-size-mb: 256
error-logs-max-files: 10
usage-statistics-enabled: {'true' if usage_enabled else 'false'}
proxy-url: ""
request-retry: 3
max-retry-credentials: 0
max-retry-interval: 30
"""
    config_path.write_text(config_text, encoding="utf-8", newline="\n")
    print(f"[OK] generated {config_path}")


if __name__ == "__main__":
    main()
